# Generated by Django 5.0.6 on 2024-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
        ),
    ]
